[[pages]]
name = "FLASHViewer"
path = "app.py"
icon = "ğŸ "

[[pages]]
name = "FLASHDeconv"
is_section = true
icon = "âš¡ï¸"

[[pages]]
path = "pages/FLASHDeconvWorkflow.py"
name = "Workflow"
icon = "âš™ï¸"

[[pages]]
path = "pages/FileUpload.py"
name = "File Upload"
icon = "ğŸ“"

[[pages]]
path = "pages/SequenceInput.py"
name = "Sequence Input"
icon = "ğŸ§µ"

[[pages]]
path = "pages/LayoutManager.py"
name = "Layout Manager"
icon = "ğŸ“ï¸"

[[pages]]
path = "pages/FLASHDeconvViewer.py"
name = "Viewer"
icon = "ğŸ‘€"

[[pages]]
path = "pages/FLASHDeconvDownload.py"
name = "Download"
icon = "â¬‡ï¸"

[[pages]]
path = "pages/FLASHFDR.py"
name = "ECDF Plot"
icon = "ğŸ“ˆ"

[[pages]]
name = "FLASHTnT"
is_section = true
icon = "ğŸ§¨"


[[pages]]
path = "pages/FLASHTaggerWorkflow.py"
name = "Workflow"
icon = "âš™ï¸"

[[pages]]
path = "pages/FileUploadTagger.py"
name = "File Upload"
icon = "ğŸ“"

[[pages]]
path = "pages/LayoutManagerTagger.py"
name = "Layout Manager"
icon = "ğŸ“ï¸"

[[pages]]
path = "pages/FLASHTaggerViewer.py"
name = "Viewer"
icon = "ğŸ‘€"

[[pages]]
path = "pages/FLASHTaggerDownload.py"
name = "Download"
icon = "â¬‡ï¸"

[[pages]]
name = "FLASHQuant"
is_section = true
icon = "ğŸ“Š"


[[pages]]
path = "pages/FileUpload_FLASHQuant.py"
name = "File Upload"
icon = "ğŸ“"

[[pages]]
path = "pages/FLASHQuantViewer.py"
name = "Viewer"
icon = "ğŸ‘€"
